package swing.examples4;

import java.awt.Frame;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Casa
 */
public class JFrameTabela extends javax.swing.JFrame {

	/**
	 * Creates new form JFrameTabela
	 */
	public JFrameTabela() {
		initComponents();

		DefaultTableModel tableModel = (DefaultTableModel) jTable.getModel();

		for (int i = 0; i < 10; i++) {
			tableModel.addRow(new Object[] { "Teste " + i, "Teste " + i, "Teste " + i, "Teste " + i });
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		jTable = new javax.swing.JTable();
		jbAlterar = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jTable.setModel(new javax.swing.table.DefaultTableModel(null,
				new String[] { "Title 1", "Title 2", "Title 3", "Title 4" }));
		jScrollPane1.setViewportView(jTable);

		jbAlterar.setText("Alterar");
		jbAlterar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jbAlterarActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup().addGap(226, 226, 226).addComponent(
										jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(layout.createSequentialGroup().addGap(426, 426, 426).addComponent(jbAlterar)))
						.addContainerGap(401, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addGap(28, 28, 28).addComponent(jbAlterar)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
						.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(89, 89, 89)));

		pack();
	}// </editor-fold>

	private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {

		if (jTable.getSelectedRow() != -1) {
			JFrameAltera tela2 = new JFrameAltera(this, true);
			tela2.preencheDados(jTable.getValueAt(jTable.getSelectedRow(), 0).toString(),
					jTable.getValueAt(jTable.getSelectedRow(), 1).toString(),
					jTable.getValueAt(jTable.getSelectedRow(), 2).toString(),
					jTable.getValueAt(jTable.getSelectedRow(), 3).toString());
			tela2.setVisible(true);

			Object[] obj = tela2.recuperaDados();
			for (int i = 0; i < obj.length && i < jTable.getColumnCount(); i++) {
				jTable.setValueAt(obj[i], jTable.getSelectedRow(), i);
			}
		}
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting
		// code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
		 * html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(JFrameTabela.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(JFrameTabela.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(JFrameTabela.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(JFrameTabela.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new JFrameTabela().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTable;
	private javax.swing.JButton jbAlterar;
	// End of variables declaration
}

/**
 *
 * @author Casa
 */
class JFrameAltera extends javax.swing.JDialog {

	/**
	 * Creates new form JFrameAltera
	 */
	public JFrameAltera(Frame parent, boolean isModal) {
		super(parent, isModal);
		initComponents();
	}

	public void preencheDados(String string1, String string2, String string3, String string4) {

		// Preenche os campos com as informações das linha selecionada no
		// "JFrameTabela"
		jf1.setText(string1);
		jf2.setText(string2);
		jf3.setText(string3);
		jf4.setText(string4);
	}

	public Object[] recuperaDados() {

		Object[] obj = { jf1.getText(), jf2.getText(), jf3.getText(), jf4.getText() };

		return obj;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jf1 = new javax.swing.JTextField();
		jf2 = new javax.swing.JTextField();
		jf3 = new javax.swing.JTextField();
		jf4 = new javax.swing.JTextField();
		jbSalvar = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jbSalvar.setText("Salvar");
		jbSalvar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jbSalvarActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup().addGap(117, 117, 117)
										.addComponent(jf1, javax.swing.GroupLayout.PREFERRED_SIZE, 70,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(32, 32, 32)
										.addComponent(jf2, javax.swing.GroupLayout.PREFERRED_SIZE, 71,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(36, 36, 36)
										.addComponent(jf3, javax.swing.GroupLayout.PREFERRED_SIZE, 79,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18).addComponent(jf4, javax.swing.GroupLayout.PREFERRED_SIZE,
												77, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(layout.createSequentialGroup().addGap(241, 241, 241).addComponent(jbSalvar)))
						.addContainerGap(458, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(69, 69, 69)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jf1, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jf2, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jf3, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jf4, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(63, 63, 63).addComponent(jbSalvar).addContainerGap(292, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>

	private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {

		// Aqui eu gravo as informações no BD (Funcionando)

		this.dispose();
	}

	// Variables declaration - do not modify
	private javax.swing.JButton jbSalvar;
	private javax.swing.JTextField jf1;
	private javax.swing.JTextField jf2;
	private javax.swing.JTextField jf3;
	private javax.swing.JTextField jf4;
	// End of variables declaration
}
