package swing.examples3;

import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.MenuElement;
import javax.swing.plaf.basic.BasicMenuBarUI;

/**
 *
 * @author Victor Alves
 */
public class JMenuBarColors2Test extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public JMenuBarColors2Test() {
        initComponents();
        customizeMenuBar(jMenuBar1);
    }
    
    private void customizeMenuBar(JMenuBar menuBar) {

        menuBar.setUI(new BasicMenuBarUI() {

            @Override
            public void paint(Graphics g, JComponent c) {
                g.setColor(Color.CYAN);
                g.fillRect(0, 0, c.getWidth(), c.getHeight());
            }

        });

        MenuElement[] menus = menuBar.getSubElements();

        for (MenuElement menuElement : menus) {

            JMenu menu = (JMenu) menuElement.getComponent();
            changeComponentColors(menu);
            menu.setOpaque(true);

            MenuElement[] menuElements = menu.getSubElements();

            for (MenuElement popupMenuElement : menuElements) {

                JPopupMenu popupMenu = (JPopupMenu) popupMenuElement.getComponent();
                popupMenu.setBorder(null);

                MenuElement[] menuItens = popupMenuElement.getSubElements();

                for (MenuElement menuItemElement : menuItens) {

                    JMenuItem menuItem = (JMenuItem) menuItemElement.getComponent();
                    changeComponentColors(menuItem);
                    menuItem.setOpaque(true);

                }
            }
        }
    }

    private void changeComponentColors(Component comp) {
        comp.setBackground(Color.cyan);
        comp.setForeground(Color.black);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        a = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        b = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuPerfil = new javax.swing.JMenu();
        jMenuEmail = new javax.swing.JMenuItem();
        jMenuPersonalidade = new javax.swing.JMenuItem();
        jMenuStatus = new javax.swing.JMenuItem();
        jMenuConfiguracoes = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenuItem();
        jMenuCloseFriend = new javax.swing.JMenu();
        jMenuJogaComigo = new javax.swing.JMenuItem();
        jMenuAdicionar = new javax.swing.JMenuItem();
        jMenuCriarTime = new javax.swing.JMenuItem();
        jMenuMelhorAmigo = new javax.swing.JMenuItem();
        jMenuMelhorTime = new javax.swing.JMenuItem();
        jMenuJogo = new javax.swing.JMenu();
        jMenuPrint = new javax.swing.JMenuItem();
        jMenuGravar = new javax.swing.JMenuItem();
        jMenuEnviar = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuAjuda = new javax.swing.JMenu();
        jMenuSuporte = new javax.swing.JMenuItem();
        jMenuPolitica = new javax.swing.JMenuItem();
        jMenuSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        a.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        a.setText("FileChooser");
        a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aActionPerformed(evt);
            }
        });
        getContentPane().add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        jLabel1.setText("path");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 540, -1, -1));

        b.setToolTipText("");
        b.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(b, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 510, 460, 60));

//        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/tg.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 740));

//        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/tg.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 1060, 470));

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 0));

        jMenuPerfil.setText("Perfil");

        jMenuEmail.setText("Administrar E-mail");
        jMenuEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEmailActionPerformed(evt);
            }
        });
        jMenuPerfil.add(jMenuEmail);

        jMenuPersonalidade.setText("Personalidade");
        jMenuPersonalidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPersonalidadeActionPerformed(evt);
            }
        });
        jMenuPerfil.add(jMenuPersonalidade);

        jMenuStatus.setText("Status");
        jMenuStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuStatusActionPerformed(evt);
            }
        });
        jMenuPerfil.add(jMenuStatus);

        jMenuConfiguracoes.setText("Configurações");
        jMenuConfiguracoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuConfiguracoesActionPerformed(evt);
            }
        });
        jMenuPerfil.add(jMenuConfiguracoes);

        jMenuSair.setText("Sair");
        jMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSairActionPerformed(evt);
            }
        });
        jMenuPerfil.add(jMenuSair);

        jMenuBar1.add(jMenuPerfil);

        jMenuCloseFriend.setText("Closefriend");

        jMenuJogaComigo.setText("Joga Comigo");
        jMenuJogaComigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuJogaComigoActionPerformed(evt);
            }
        });
        jMenuCloseFriend.add(jMenuJogaComigo);

        jMenuAdicionar.setText("Adicionar");
        jMenuAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAdicionarActionPerformed(evt);
            }
        });
        jMenuCloseFriend.add(jMenuAdicionar);

        jMenuCriarTime.setText("Criar Time");
        jMenuCriarTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCriarTimeActionPerformed(evt);
            }
        });
        jMenuCloseFriend.add(jMenuCriarTime);

        jMenuMelhorAmigo.setText("Melhor Amigo");
        jMenuMelhorAmigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuMelhorAmigoActionPerformed(evt);
            }
        });
        jMenuCloseFriend.add(jMenuMelhorAmigo);

        jMenuMelhorTime.setText("Melhor Time");
        jMenuMelhorTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuMelhorTimeActionPerformed(evt);
            }
        });
        jMenuCloseFriend.add(jMenuMelhorTime);

        jMenuBar1.add(jMenuCloseFriend);

        jMenuJogo.setText("Em Jogo");

        jMenuPrint.setText("PrintScreen");
        jMenuPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPrintActionPerformed(evt);
            }
        });
        jMenuJogo.add(jMenuPrint);

        jMenuGravar.setText("Gravar Vídeo");
        jMenuGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuGravarActionPerformed(evt);
            }
        });
        jMenuJogo.add(jMenuGravar);

        jMenuEnviar.setText("Enviar Para o MYCLOSE");
        jMenuEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEnviarActionPerformed(evt);
            }
        });
        jMenuJogo.add(jMenuEnviar);

        jMenuBar1.add(jMenuJogo);

        jMenu1.setText("Bate Papo");

        jMenuItem1.setText("Amigos Online");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("jMenuItem2");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenuAjuda.setText("Ajuda");

        jMenuSuporte.setText("Suporte CloseFriend");
        jMenuSuporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSuporteActionPerformed(evt);
            }
        });
        jMenuAjuda.add(jMenuSuporte);

        jMenuPolitica.setText("Política de Privacidade");
        jMenuPolitica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPoliticaActionPerformed(evt);
            }
        });
        jMenuAjuda.add(jMenuPolitica);

        jMenuSobre.setText("Sobre a CloseFriend");
        jMenuSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSobreActionPerformed(evt);
            }
        });
        jMenuAjuda.add(jMenuSobre);

        jMenuBar1.add(jMenuAjuda);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1382, 803));
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void jMenuEmailActionPerformed(java.awt.event.ActionEvent evt) {                                           
//        Email tela = new Email();
//        tela.setVisible(true);
//        dispose();
    }                                          

    private void jMenuPersonalidadeActionPerformed(java.awt.event.ActionEvent evt) {                                                   
//        Personalidade tela = new Personalidade();
//        tela.setVisible(true); 
//        dispose();
    }                                                  

    private void jMenuStatusActionPerformed(java.awt.event.ActionEvent evt) {                                            
//        Status tela = new Status();
//        tela.setVisible(true);  
//        dispose();
    }                                           

    private void jMenuConfiguracoesActionPerformed(java.awt.event.ActionEvent evt) {                                                   
//        Configuracoes tela = new Configuracoes();
//        tela.setVisible(true);
//        dispose();
    }                                                  

    private void jMenuSairActionPerformed(java.awt.event.ActionEvent evt) {                                          
//        Sair tela = new Sair();
//        tela.setVisible(true); 
//        dispose();
    }                                         

    private void jMenuJogaComigoActionPerformed(java.awt.event.ActionEvent evt) {                                                
//        JogaComigo tela = new JogaComigo();
//        tela.setVisible(true);
//        dispose();
    }                                               

    private void jMenuAdicionarActionPerformed(java.awt.event.ActionEvent evt) {                                               
//        Adicionar tela = new Adicionar();
//        tela.setVisible(true); 
//        dispose();
    }                                              

    private void jMenuCriarTimeActionPerformed(java.awt.event.ActionEvent evt) {                                               
//        CriarGrupo tela = new CriarGrupo();
//        tela.setVisible(true); 
//        dispose();
    }                                              

    private void jMenuMelhorAmigoActionPerformed(java.awt.event.ActionEvent evt) {                                                 
//        MelhorAmigo tela = new MelhorAmigo();
//        tela.setVisible(true); 
//        dispose();
    }                                                

    private void jMenuMelhorTimeActionPerformed(java.awt.event.ActionEvent evt) {                                                
//        MelhorTime tela = new MelhorTime();
//        tela.setVisible(true); 
//        dispose();
    }                                               

    private void jMenuPrintActionPerformed(java.awt.event.ActionEvent evt) {                                           
//        Print tela = new Print();
//        tela.setVisible(true);
//        dispose();
    }                                          

    private void jMenuGravarActionPerformed(java.awt.event.ActionEvent evt) {                                            
//        GravarVideo tela = new GravarVideo();
//        tela.setVisible(true); 
//        dispose();
    }                                           

    private void jMenuEnviarActionPerformed(java.awt.event.ActionEvent evt) {                                            
//        EnviarMyClose tela = new EnviarMyClose();
//        tela.setVisible(true);
//        dispose();
    }                                           

    private void jMenuSuporteActionPerformed(java.awt.event.ActionEvent evt) {                                             
//       Suporte tela = new Suporte();
//        tela.setVisible(true); 
//        dispose();
    }                                            

    private void jMenuPoliticaActionPerformed(java.awt.event.ActionEvent evt) {                                              
//        Politica tela = new Politica();
//        tela.setVisible(true); 
//        dispose();
    }                                             

    private void jMenuSobreActionPerformed(java.awt.event.ActionEvent evt) {                                           
//        Sobre tela = new Sobre();
//        tela.setVisible(true); 
//        dispose();
    }                                          

    private void aActionPerformed(java.awt.event.ActionEvent evt) {                                  
       JFileChooser chooser=new JFileChooser();
       chooser.showOpenDialog(null);
       File f= chooser.getSelectedFile();
       String filename=f.getAbsolutePath();
       b.setText(filename);
       ImageIcon icon=new ImageIcon(filename);
       a.setIcon(icon);
    }                                 


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JMenuBarColors2Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JMenuBarColors2Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JMenuBarColors2Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JMenuBarColors2Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JMenuBarColors2Test().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton a;
    private javax.swing.JLabel b;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuAdicionar;
    private javax.swing.JMenu jMenuAjuda;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCloseFriend;
    private javax.swing.JMenuItem jMenuConfiguracoes;
    private javax.swing.JMenuItem jMenuCriarTime;
    private javax.swing.JMenuItem jMenuEmail;
    private javax.swing.JMenuItem jMenuEnviar;
    private javax.swing.JMenuItem jMenuGravar;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuJogaComigo;
    private javax.swing.JMenu jMenuJogo;
    private javax.swing.JMenuItem jMenuMelhorAmigo;
    private javax.swing.JMenuItem jMenuMelhorTime;
    private javax.swing.JMenu jMenuPerfil;
    private javax.swing.JMenuItem jMenuPersonalidade;
    private javax.swing.JMenuItem jMenuPolitica;
    private javax.swing.JMenuItem jMenuPrint;
    private javax.swing.JMenuItem jMenuSair;
    private javax.swing.JMenuItem jMenuSobre;
    private javax.swing.JMenuItem jMenuStatus;
    private javax.swing.JMenuItem jMenuSuporte;
    // End of variables declaration                   
}
