package swing_examples;

import javax.swing.JDesktopPane;
import javax.swing.JFrame;
//import Classes.Funcionario;
//import ClassesDAO.FuncionarioDAO;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Douglas
 */
public class Tela_AlterarFuncionario extends javax.swing.JInternalFrame {

	/**
	 * Creates new form Tela_IncluirFuncionario
	 */

	public static void main(String[] args) {
		javax.swing.SwingUtilities.invokeLater(new Runnable() {
			public void run() {
				JFrame f = new JFrame();
				JDesktopPane desktop = new JDesktopPane();
				Tela_AlterarFuncionario internalframe = new Tela_AlterarFuncionario();
				internalframe.setVisible(true);
				desktop.add(internalframe);
				f.setContentPane(desktop);
				f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
				f.setVisible(true);
			}
		});

	}

	public Tela_AlterarFuncionario() {

		initComponents();

		Btn_Alterar.setEnabled(false);

		DefaultTableModel model = (DefaultTableModel) TBL_AlterarFuncionarios.getModel();

		// FuncionarioDAO dao=new FuncionarioDAO();
		//
		// for(Funcionario func: dao.Listsubtela()){
		//
		// model.addRow(new Object[]{
		// func.getID_Funcionario(),
		// func.getNome(),
		// func.getDatadeAdmissao(),
		// func.getCargo(),
		// });
		// }

		// for (Funcionario func: dao.ListcombNome()){
		// Comb_Nome.addItem(func.getNome() );
		// }

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		Inc_Sex = new javax.swing.ButtonGroup();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		Txt_DataNasc = new javax.swing.JFormattedTextField();
		jLabel3 = new javax.swing.JLabel();
		Rad_Masc = new javax.swing.JRadioButton();
		Rad_Fem = new javax.swing.JRadioButton();
		Btn_Alterar = new javax.swing.JButton();
		jLabel4 = new javax.swing.JLabel();
		Txt_DataAdm = new javax.swing.JFormattedTextField();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		Txt_CEP = new javax.swing.JFormattedTextField();
		jLabel7 = new javax.swing.JLabel();
		Txt_CPF = new javax.swing.JFormattedTextField();
		jLabel8 = new javax.swing.JLabel();
		Txt_RG = new javax.swing.JFormattedTextField();
		jLabel9 = new javax.swing.JLabel();
		Comb_Estado = new javax.swing.JComboBox<>();
		jLabel10 = new javax.swing.JLabel();
		Txt_Cidade = new javax.swing.JTextField();
		jLabel11 = new javax.swing.JLabel();
		Txt_Bairro = new javax.swing.JTextField();
		jLabel12 = new javax.swing.JLabel();
		Txt_Endereco = new javax.swing.JTextField();
		jLabel13 = new javax.swing.JLabel();
		Txt_Tel = new javax.swing.JFormattedTextField();
		jLabel14 = new javax.swing.JLabel();
		Txt_Cel = new javax.swing.JFormattedTextField();
		jLabel15 = new javax.swing.JLabel();
		Txt_Email = new javax.swing.JTextField();
		jLabel16 = new javax.swing.JLabel();
		Txt_Cargo = new javax.swing.JTextField();
		jLabel17 = new javax.swing.JLabel();
		Comb_NivelEscolaridade = new javax.swing.JComboBox<>();
		Btn_Limpar = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		TBL_AlterarFuncionarios = new javax.swing.JTable();
		Btn_Consultar = new javax.swing.JButton();
		Comb_Nome = new javax.swing.JComboBox<>();
		Comb_EstadoCivil = new javax.swing.JComboBox<>();
		jLabel18 = new javax.swing.JLabel();
		Txt_IDFuncionario = new javax.swing.JTextField();

		setClosable(true);
		setIconifiable(true);
		setTitle("AlterarFuncionario");
		try {
			setSelected(true);
		} catch (java.beans.PropertyVetoException e1) {
			e1.printStackTrace();
		}
		setVisible(true);

		jLabel1.setText("Nome:");

		jLabel2.setText("Data de Nascimento:");

		Txt_DataNasc.setEditable(false);
		try {
			Txt_DataNasc.setFormatterFactory(
					new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
		} catch (java.text.ParseException ex) {
			ex.printStackTrace();
		}

		jLabel3.setText("Sexo:");

		Inc_Sex.add(Rad_Masc);
		Rad_Masc.setText("Masculino");

		Inc_Sex.add(Rad_Fem);
		Rad_Fem.setText("Feminino");

		Btn_Alterar.setText("Alterar");
		Btn_Alterar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				Btn_AlterarActionPerformed(evt);
			}
		});

		jLabel4.setText("Data de Admissão:");

		Txt_DataAdm.setEditable(false);
		try {
			Txt_DataAdm.setFormatterFactory(
					new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
		} catch (java.text.ParseException ex) {
			ex.printStackTrace();
		}

		jLabel5.setText("Estado Civil:");

		jLabel6.setText("CEP:");

		Txt_CEP.setEditable(false);
		try {
			Txt_CEP.setFormatterFactory(
					new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
		} catch (java.text.ParseException ex) {
			ex.printStackTrace();
		}

		jLabel7.setText("CPF:");

		Txt_CPF.setEditable(false);
		try {
			Txt_CPF.setFormatterFactory(
					new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
		} catch (java.text.ParseException ex) {
			ex.printStackTrace();
		}

		jLabel8.setText("RG:");

		Txt_RG.setEditable(false);
		try {
			Txt_RG.setFormatterFactory(
					new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
		} catch (java.text.ParseException ex) {
			ex.printStackTrace();
		}

		jLabel9.setText("Estado:");

		Comb_Estado.setModel(new javax.swing.DefaultComboBoxModel<>(
				new String[] { "Selecione", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS",
						"MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

		jLabel10.setText("Cidade:");

		Txt_Cidade.setEditable(false);

		jLabel11.setText("Bairro:");

		Txt_Bairro.setEditable(false);

		jLabel12.setText("Endereco:");

		Txt_Endereco.setEditable(false);

		jLabel13.setText("TEL:");

		Txt_Tel.setEditable(false);
		try {
			Txt_Tel.setFormatterFactory(
					new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
		} catch (java.text.ParseException ex) {
			ex.printStackTrace();
		}

		jLabel14.setText("Cel:");

		Txt_Cel.setEditable(false);
		try {
			Txt_Cel.setFormatterFactory(
					new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
		} catch (java.text.ParseException ex) {
			ex.printStackTrace();
		}

		jLabel15.setText("Email:");

		Txt_Email.setEditable(false);

		jLabel16.setText("Cargo:");

		Txt_Cargo.setEditable(false);

		jLabel17.setText("Nivel de Escolaridade:");

		Comb_NivelEscolaridade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {
				"Ensino Fundamental Incompleto", "Ensino Fundamental Completo", "Ensino Médio Incompleto",
				"Ensino Médio Completo", "Ensino Superior Incompleto", "Ensino Superior Completo" }));

		Btn_Limpar.setText("Resetar");
		Btn_Limpar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				Btn_LimparActionPerformed(evt);
			}
		});

		TBL_AlterarFuncionarios.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {

		}, new String[] { "ID_Funcionario", "Nome", "Data de Admissão", "Cargo" }) {
			boolean[] canEdit = new boolean[] { false, false, false, false };

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		jScrollPane1.setViewportView(TBL_AlterarFuncionarios);

		Btn_Consultar.setText("Consultar");
		Btn_Consultar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				Btn_ConsultarActionPerformed(evt);
			}
		});

		Comb_EstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(
				new String[] { "Selecione", "Solteiro", "Casado", "Divorciado", "Viuvo" }));

		jLabel18.setText("ID:");

		Txt_IDFuncionario.setEditable(false);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout
						.createSequentialGroup().addGroup(layout.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout
										.createSequentialGroup().addContainerGap().addGroup(
												layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
														.addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout
																.createSequentialGroup()
																.addComponent(jLabel11)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addComponent(Txt_Bairro,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 120,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout
																.createSequentialGroup().addComponent(jLabel14)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(Txt_Cel,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		105, javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(18, 18, 18).addComponent(jLabel15)))
										.addGap(1, 1, 1)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
												.addGroup(layout.createSequentialGroup()
														.addComponent(Txt_Email, javax.swing.GroupLayout.PREFERRED_SIZE,
																157, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
														.addComponent(jLabel16)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(
																Txt_Cargo, javax.swing.GroupLayout.PREFERRED_SIZE,
																138, javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(layout.createSequentialGroup().addComponent(jLabel12)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(Txt_Endereco,
																javax.swing.GroupLayout.PREFERRED_SIZE, 128,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGap(18, 18, 18).addComponent(jLabel13)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(Txt_Tel, javax.swing.GroupLayout.PREFERRED_SIZE,
																121, javax.swing.GroupLayout.PREFERRED_SIZE))))
								.addGroup(layout.createSequentialGroup().addGap(12, 12, 12).addComponent(jLabel8)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(Txt_RG, javax.swing.GroupLayout.PREFERRED_SIZE, 94,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(20, 20, 20).addComponent(jLabel6)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(Txt_CEP, javax.swing.GroupLayout.PREFERRED_SIZE, 130,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18).addComponent(jLabel10)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(Txt_Cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 121,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(jLabel3)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(Rad_Masc)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(Rad_Fem).addGap(18, 18, 18).addComponent(jLabel7)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(Txt_CPF, javax.swing.GroupLayout.PREFERRED_SIZE, 136,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18).addComponent(jLabel9)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(Comb_Estado, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(layout.createSequentialGroup().addContainerGap().addGroup(layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(layout.createSequentialGroup().addComponent(jLabel2)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(Txt_DataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 107,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(18, 18, 18).addComponent(jLabel5)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(Comb_EstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(layout.createSequentialGroup().addComponent(jLabel4)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
												.addComponent(Txt_DataAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 157,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
												.addComponent(jLabel1)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(Comb_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 210,
														javax.swing.GroupLayout.PREFERRED_SIZE))))
								.addGroup(layout.createSequentialGroup().addGap(54, 54, 54)
										.addComponent(Btn_Consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 91,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18).addComponent(Btn_Alterar).addGap(26, 26, 26)
										.addComponent(Btn_Limpar))
								.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(jLabel17)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(Comb_NivelEscolaridade, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(jLabel18)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(Txt_IDFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 154,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
						.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap()));
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
						.createSequentialGroup().addContainerGap().addGroup(layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
										.createSequentialGroup().addGap(8, 8, 8).addGroup(
												layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel18).addComponent(
																Txt_IDFuncionario,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel4)
												.addComponent(Txt_DataAdm, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel1).addComponent(Comb_Nome,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel2)
												.addComponent(Txt_DataNasc, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel5).addComponent(Comb_EstadoCivil,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel3).addComponent(Rad_Masc).addComponent(Rad_Fem)
												.addComponent(jLabel7)
												.addComponent(Txt_CPF, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel9).addComponent(Comb_Estado,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel8)
												.addComponent(Txt_RG, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel6)
												.addComponent(Txt_CEP, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel10).addComponent(Txt_Cidade,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(24, 24, 24)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel11)
												.addComponent(Txt_Bairro, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel12)
												.addComponent(Txt_Endereco, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel13)
												.addComponent(Txt_Tel, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(23, 23, 23)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel14)
												.addComponent(Txt_Cel, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel15)
												.addComponent(Txt_Email, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel16).addComponent(Txt_Cargo,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(52, 52, 52)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel17).addComponent(Comb_NivelEscolaridade,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(25, 25, 25)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(Btn_Alterar).addComponent(Btn_Limpar)
												.addComponent(Btn_Consultar)))
								.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap(38, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>

	private void Btn_AlterarActionPerformed(java.awt.event.ActionEvent evt) {

		String sexo = null;
		if (Rad_Masc.isSelected()) {
			sexo = "Masculino";
		}

		if (Rad_Fem.isSelected()) {
			sexo = "Feminino";
		}

		//
		// Funcionario f=new Funcionario();
		// FuncionarioDAO dao=new FuncionarioDAO();
		// f.setID_Funcionario(Integer.parseInt(Txt_IDFuncionario.getText()));
		// f.setDatadeAdmissao(Txt_DataAdm.getText());
		// f.setNome(Comb_Nome.getSelectedItem().toString());
		// f.setEstadoCivil(Comb_EstadoCivil.getSelectedItem().toString());
		// f.setSexo(sexo);
		// f.setCep(Txt_CEP.getText());
		// f.setCpf(Txt_CPF.getText());
		// f.setRg(Txt_RG.getText());
		// f.setDatadeNascimento(Txt_DataNasc.getText());
		// f.setEstadoCivil(Comb_Estado.getSelectedItem().toString());
		// f.setCidade(Txt_Cidade.getText());
		// f.setBairro(Txt_Bairro.getText());
		// f.setEndereco(Txt_Endereco.getText());
		// f.setTel(Txt_Tel.getText());
		// f.setCel(Txt_Cel.getText());
		// f.setEmail(Txt_Email.getText());
		// f.setCargo(Txt_Cargo.getText());
		// f.setNiveldeEscolaridade(Comb_NivelEscolaridade.getSelectedItem().toString());
		// dao.inserir(f);

		Txt_DataAdm.setEditable(false);
		Txt_DataNasc.setEditable(false);
		Comb_EstadoCivil.setEnabled(false);
		Txt_CPF.setEditable(false);
		Comb_Estado.setEnabled(false);
		Txt_RG.setEditable(false);
		Txt_CEP.setEditable(false);
		Txt_Cidade.setEditable(false);
		Txt_Bairro.setEditable(false);
		Txt_Endereco.setEditable(false);
		Txt_Tel.setEditable(false);
		Txt_Cel.setEditable(false);
		Txt_Email.setEditable(false);
		Txt_Cargo.setEditable(false);
		Comb_NivelEscolaridade.setEnabled(false);
		Btn_Alterar.setEnabled(false);

		Txt_DataAdm.setText("");
		Txt_DataNasc.setText("");
		Comb_EstadoCivil.setSelectedItem(0);
		Txt_CPF.setText("");
		Comb_Estado.setSelectedItem(0);
		Txt_RG.setText("");
		Txt_CEP.setText("");
		Txt_Cidade.setText("");
		Txt_Bairro.setText("");
		Txt_Endereco.setText("");
		Txt_Tel.setText("");
		Txt_Cel.setText("");
		Txt_Email.setText("");
		Txt_Cargo.setText("");
		Comb_NivelEscolaridade.setSelectedItem(0);
	}

	private void Btn_ConsultarActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:

		// FuncionarioDAO dao=new FuncionarioDAO();
		//
		// for(Funcionario func: dao.Listalterar()){
		//
		//
		// Txt_IDFuncionario.setText(String.valueOf ( func.getID_Funcionario())
		// );
		// Txt_DataAdm.setText(func.getDatadeAdmissao() );
		// Txt_DataNasc.setText(String.valueOf ( func.getDatadeNascimento()) );
		// Comb_EstadoCivil.setSelectedItem(String.valueOf
		// (func.getEstadoCivil()));
		// Txt_CPF.setText(func.getCpf());
		// Comb_Estado.setSelectedItem(String.valueOf (func.getEstado()));
		// Txt_RG.setText(func.getRg());
		// Txt_CEP.setText(func.getCep());
		// Txt_Cidade.setText(func.getCidade());
		// Txt_Bairro.setText(func.getBairro());
		// Txt_Endereco.setText(func.getEndereco());
		// Txt_Tel.setText(func.getTel());
		// Txt_Cel.setText(func.getCel());
		// Txt_Email.setText(func.getEmail());
		// Txt_Cargo.setText(func.getCargo());
		// Comb_NivelEscolaridade.setSelectedItem(String.valueOf(func.getNiveldeEscolaridade()));
		//
		// }

		Txt_DataAdm.setEditable(true);
		Txt_DataNasc.setEditable(true);
		Comb_EstadoCivil.setEnabled(true);
		Txt_CPF.setEditable(true);
		Comb_Estado.setEnabled(true);
		Txt_RG.setEditable(true);
		Txt_CEP.setEditable(true);
		Txt_Cidade.setEditable(true);
		Txt_Bairro.setEditable(true);
		Txt_Endereco.setEditable(true);
		Txt_Tel.setEditable(true);
		Txt_Cel.setEditable(true);
		Txt_Email.setEditable(true);
		Txt_Cargo.setEditable(true);
		Comb_NivelEscolaridade.setEnabled(true);
		Btn_Alterar.setEnabled(true);
	}

	private void Btn_LimparActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		Txt_IDFuncionario.setText("");
		Comb_Nome.setSelectedItem(0);
		Txt_DataAdm.setText("");
		Txt_DataNasc.setText("");
		Comb_EstadoCivil.setSelectedItem(0);
		Txt_CPF.setText("");
		Comb_Estado.setSelectedItem(0);
		Txt_RG.setText("");
		Txt_CEP.setText("");
		Txt_Cidade.setText("");
		Txt_Bairro.setText("");
		Txt_Endereco.setText("");
		Txt_Tel.setText("");
		Txt_Cel.setText("");
		Txt_Email.setText("");
		Txt_Cargo.setText("");
		Comb_NivelEscolaridade.setSelectedItem(0);

	}

	// Variables declaration - do not modify
	private javax.swing.JButton Btn_Alterar;
	private javax.swing.JButton Btn_Consultar;
	private javax.swing.JButton Btn_Limpar;
	private javax.swing.JComboBox<String> Comb_Estado;
	private javax.swing.JComboBox<String> Comb_EstadoCivil;
	private javax.swing.JComboBox<String> Comb_NivelEscolaridade;
	private javax.swing.JComboBox<String> Comb_Nome;
	private javax.swing.ButtonGroup Inc_Sex;
	private javax.swing.JRadioButton Rad_Fem;
	private javax.swing.JRadioButton Rad_Masc;
	private javax.swing.JTable TBL_AlterarFuncionarios;
	private javax.swing.JTextField Txt_Bairro;
	private javax.swing.JFormattedTextField Txt_CEP;
	private javax.swing.JFormattedTextField Txt_CPF;
	private javax.swing.JTextField Txt_Cargo;
	private javax.swing.JFormattedTextField Txt_Cel;
	private javax.swing.JTextField Txt_Cidade;
	private javax.swing.JFormattedTextField Txt_DataAdm;
	private javax.swing.JFormattedTextField Txt_DataNasc;
	private javax.swing.JTextField Txt_Email;
	private javax.swing.JTextField Txt_Endereco;
	private javax.swing.JTextField Txt_IDFuncionario;
	private javax.swing.JFormattedTextField Txt_RG;
	private javax.swing.JFormattedTextField Txt_Tel;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel15;
	private javax.swing.JLabel jLabel16;
	private javax.swing.JLabel jLabel17;
	private javax.swing.JLabel jLabel18;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JScrollPane jScrollPane1;
	// End of variables declaration
}